# Generated by Django 6.0.6 on 2026-06-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10),
        ),
    ]
