# Generated by Django 6.0.6 on 2026-06-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_django', '0002_alter_recurring_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurring',
            name='datetimes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
