# Generated by Django 6.0.6 on 2026-07-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_django', '0003_alter_recurring_datetimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('system', 'System'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=6),
        ),
    ]
