# Generated by Django 5.2.4 on 2025-08-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')])),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('investment', 'Investment'), ('savings', 'Savings'), ('credit', 'Credit Card'), ('loan', 'Loan'), ('other', 'Other')], max_length=50)),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quetzal_app.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quetzal_app.account')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quetzal_app.category')),
                ('currency_ref', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='quetzal_app.currency')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quetzal_app.user')),
            ],
        ),
    ]
