# Generated by Django 5.2.4 on 2025-08-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_app', '0004_alter_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_id',
            new_name='user',
        ),
    ]
