# Generated by Django 5.2.4 on 2025-08-25 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_app', '0009_remove_transaction_currency_ref_transaction_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='category_id',
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),
    ]
