# Generated by Django 5.2.4 on 2025-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_app', '0011_transaction_account_transaction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=10, null=True),
        ),
    ]
