# Generated by Django 5.2.4 on 2025-08-26 17:41

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quetzal_app', '0013_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
